export const avatarsForPreview = [
  'accessoriesType=Prescription02&clotheColor=Black&clotheType=Overall&eyeType=Happy&eyebrowType=SadConcernedNatural&facialHairColor=BlondeGolden&facialHairType=MoustacheFancy&hairColor=Blonde&mouthType=ScreamOpen&skinColor=Pale&topType=LongHairBob',
  'accessoriesType=Wayfarers&clotheColor=PastelYellow&clotheType=BlazerSweater&eyeType=Cry&eyebrowType=RaisedExcited&facialHairColor=Blonde&facialHairType=MoustacheFancy&hairColor=Black&hatColor=Pink&mouthType=Smile&skinColor=Yellow&topType=ShortHairFrizzle',
  'accessoriesType=Prescription02&clotheColor=Gray02&clotheType=Hoodie&eyeType=Wink&eyebrowType=FlatNatural&facialHairColor=Platinum&facialHairType=BeardMedium&hairColor=SilverGray&hatColor=Gray01&mouthType=Tongue&skinColor=Brown&topType=ShortHairShaggyMullet',
  'accessoriesType=Round&clotheColor=PastelGreen&clotheType=ShirtScoopNeck&eyeType=Hearts&eyebrowType=UpDownNatural&facialHairColor=BlondeGolden&facialHairType=BeardMedium&hairColor=Auburn&hatColor=White&mouthType=Sad&skinColor=Light&topType=Hijab',
  'accessoriesType=Blank&clotheColor=Gray02&clotheType=GraphicShirt&eyeType=Surprised&eyebrowType=UnibrowNatural&facialHairColor=BlondeGolden&facialHairType=MoustacheMagnum&graphicType=Hola&hairColor=BlondeGolden&hatColor=PastelYellow&mouthType=Disbelief&skinColor=Yellow&topType=WinterHat2',
  'accessoriesType=Kurt&clotheColor=PastelOrange&clotheType=BlazerSweater&eyeType=Default&eyebrowType=UpDownNatural&facialHairColor=Black&facialHairType=BeardMedium&graphicType=SkullOutline&hairColor=BrownDark&hatColor=PastelBlue&mouthType=Vomit&skinColor=Tanned&topType=ShortHairDreads01',
  'accessoriesType=Blank&clotheColor=Blue03&clotheType=Overall&eyeType=Default&eyebrowType=UpDown&facialHairColor=BrownDark&facialHairType=BeardLight&graphicType=Cumbia&hairColor=Auburn&hatColor=Red&mouthType=Smile&skinColor=Light&topType=WinterHat2',
  'accessoriesType=Kurt&clotheColor=Blue02&clotheType=ShirtVNeck&eyeType=Happy&eyebrowType=Default&facialHairColor=BrownDark&facialHairType=Blank&graphicType=Hola&hairColor=Platinum&hatColor=PastelBlue&mouthType=Serious&skinColor=Light&topType=LongHairNotTooLong',
  'accessoriesType=Sunglasses&clotheColor=Gray02&clotheType=ShirtVNeck&eyeType=Happy&eyebrowType=Default&facialHairColor=Blonde&facialHairType=Blank&graphicType=SkullOutline&hairColor=Red&hatColor=PastelGreen&mouthType=Serious&skinColor=DarkBrown&topType=LongHairBun',
  'accessoriesType=Prescription02&clotheColor=PastelRed&clotheType=BlazerSweater&eyeType=Dizzy&eyebrowType=AngryNatural&facialHairColor=Red&facialHairType=BeardLight&graphicType=Hola&hairColor=Blonde&hatColor=Blue01&mouthType=Smile&skinColor=Light&topType=LongHairFrida'
]
